name: CI
on: [workflow_dispatch]

# 在全局范围开启 Node.js 24 强制选项
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # 即使是 v4，设置了环境变量后也会用 Node 24 运行

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Voxy-1.20.1-Jar
          path: build/libs/!(*-sources|*-dev).jar
