name: CI
on: [workflow_dispatch]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  GRADLE_OPTS: -Xmx4g

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup JDK 21  # <--- 这里改为 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'
          cache: 'gradle'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build --stacktrace

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: Voxy-1.20.1-Build-Output
          # 修改这里：直接抓取所有 jar 文件，避免复杂的排除语法出错
          path: build/libs/*.jar
